spring:
  application:
    name: regist-web
  redis:
    host: 192.168.2.159
    port: 6379
    password: java1908
    jedis:
      pool:
        max-active: 20

server:
  port: 7762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

